In [1]:
import pandas as pd
print("¡Hola, Jupyter en VS Code!")

¡Hola, Jupyter en VS Code!

In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\aleja\Workspace\Python\Proyecto_Envasados\data\raw\disponibilidad_1_semana.csv")
df1 = pd.read_csv(r"C:\Users\aleja\Workspace\Python\Proyecto_Envasados\data\raw\calidad_1_semana.csv")
df.head()

,Unnamed: 0,result,table,_start,_stop,_time,_value,_field,_measurement,device_id,formato,linea,stopping_reason
0,NaN,NaN,0,2025-02-19T18:05:30.379916796Z,2025-02-26T18:05:30.379916796Z,2025-02-19T18:05:59.6986263Z,Produciendo,availability,availability-metric,01-Despaletizadora1,6,linea01,-
1,NaN,NaN,0,2025-02-19T18:05:30.379916796Z,2025-02-26T18:05:30.379916796Z,2025-02-19T18:06:29.7302535Z,Produciendo,availability,availability-metric,01-Despaletizadora1,6,linea01,-
2,NaN,NaN,0,2025-02-19T18:05:30.379916796Z,2025-02-26T18:05:30.379916796Z,2025-02-19T18:06:59.7602257Z,Produciendo,availability,availability-metric,01-Despaletizadora1,6,linea01,-
3,NaN,NaN,0,2025-02-19T18:05:30.379916796Z,2025-02-26T18:05:30.379916796Z,2025-02-19T18:07:29.7647353Z,Produciendo,availability,availability-metric,01-Despaletizadora1,6,linea01,-
4,NaN,NaN,0,2025-02-19T18:05:30.379916796Z,2025-02-26T18:05:30.379916796Z,2025-02-19T18:07:59.7679621Z,Produciendo,availability,availability-metric,01-Despaletizadora1,6,linea01,-

In [3]:
df1.head()

,Unnamed: 0,result,table,_start,_stop,_time,_value,ILC_velocity,_field,_measurement,device_id,linea,product_id,real_velocity,velocity
0,NaN,NaN,0,2025-02-19T18:00:14.412314098Z,2025-02-26T18:00:14.412314098Z,2025-02-19T18:00:29.9732831Z,0.0,12000.0,approved,quality-metric,03-Monoblock1,linea01,6,0.0,11000.0
1,NaN,NaN,0,2025-02-19T18:00:14.412314098Z,2025-02-26T18:00:14.412314098Z,2025-02-19T18:00:59.9764592Z,0.0,12000.0,approved,quality-metric,03-Monoblock1,linea01,6,0.0,11000.0
2,NaN,NaN,0,2025-02-19T18:00:14.412314098Z,2025-02-26T18:00:14.412314098Z,2025-02-19T18:03:30.0654951Z,0.0,12000.0,approved,quality-metric,03-Monoblock1,linea01,6,0.0,11000.0
3,NaN,NaN,0,2025-02-19T18:00:14.412314098Z,2025-02-26T18:00:14.412314098Z,2025-02-19T18:04:00.072907Z,0.0,12000.0,approved,quality-metric,03-Monoblock1,linea01,6,0.0,11000.0
4,NaN,NaN,0,2025-02-19T18:00:14.412314098Z,2025-02-26T18:00:14.412314098Z,2025-02-19T18:04:30.1033248Z,0.0,12000.0,approved,quality-metric,03-Monoblock1,linea01,6,0.0,11000.0